from pathlib import Path
import json,html,re,zipfile
from urllib.parse import urlencode
root=Path('public/campaigns/visitorping-launch')
posts=[{'platform':'X','id':'x_demo','text':'Your website gets a visitor. Your iPhone pings.\n\nI built VisitorPing to show live website activity and send visitor notifications to your iPhone.\n\nHere’s a 15-second preview using example data.','url':'https://visitorping.com/?utm_source=x&utm_medium=organic_social&utm_campaign=first_visitors_free&utm_content=demo','asset':'assets/visitorping-demo.mp4'}, {'platform':'X','id':'x_question','text':'Website owners: when someone visits your site, would you want an iPhone notification—or do you prefer checking a dashboard?\n\nI’m building VisitorPing around both. Curious which you’d actually use.','url':None,'asset':None},{'platform':'X','id':'x_install','text':'VisitorPing works with SaaS websites, WordPress pages and Shopify stores.\n\nAdd your website, install the tracker, and connect your iPhone for visitor notifications.\n\nBuilt it? Now see when someone visits.','url':'https://visitorping.com/?utm_source=x&utm_medium=organic_social&utm_campaign=first_visitors_free&utm_content=setup','asset':'assets/ad-refreshing.png'}, {'platform':'Reddit — r/SideProject','id':'reddit_sideproject','title':'VisitorPing - Live website visitors and iPhone notifications','text':'I built VisitorPing for website owners who want to notice visits as they happen.\n\nIt shows visitor activity in a live web dashboard and sends notifications to your iPhone. It works with SaaS websites, WordPress pages, Shopify stores and other supported sites.\n\nThe demo uses example data. Visitors are anonymous by default; it doesn’t reveal someone’s name just because they visited.\n\nThe product is working, but reaching the people who want it is the part I’m figuring out. If you run a website, would you use the live dashboard, the phone notifications, or both?\n\nI’m the creator. Website: https://visitorping.com/','url':'https://visitorping.com/','asset':'assets/visitorping-demo.mp4'}]
for p in posts:
 if p['platform']=='X':
  weighted=len(p['text'])+(25 if p['url'] else 0)
  assert weighted<=280,(p['id'],weighted)
plan={'status':'draft_awaiting_authenticated_publishing_access','spend_cap_usd':0,'paid_campaigns_enabled':False,'channels':['X','Reddit'],'handles':{'x':'serhansarii','reddit':'serhansari83'},'goal':'Five website owners install tracking and record a first visitor; target, not forecast','posts':posts,'sequence':['Publish X demo after account/history check','Submit one r/SideProject introduction if account eligible','Read responses before any follow-up','Use the X question or setup post only when it adds new context'],'rules_checked':'2026-09-10','excluded':['r/SaaS: disallows AI-generated text and restricts promotion','r/startups: not approved as a generic launch destination'],'measurement':'UTMs identify X landing sessions; Reddit uses a clean URL. Campaign-to-activation attribution is not verified. No claims that aggregate signups came from a post.'}
(root/'campaign.json').write_text(json.dumps(plan,indent=2,ensure_ascii=False))
old=(root/'index.html').read_text()
if not (root/'paid-review-archived.html').exists():(root/'paid-review-archived.html').write_text(old)
style=re.search(r'<style>(.*?)</style>',old,re.S).group(1)
cards=''
for p in posts:
 content=(p.get('title','')+'\n\n' if p.get('title') else '')+p['text']+ ('\n\n'+p['url'] if p['platform']=='X' and p['url'] else '')
 cards+='<article class="section"><h2>'+html.escape(p['platform'])+'</h2><blockquote style="white-space:pre-wrap">'+html.escape(content)+'</blockquote>'
 if p['platform']=='X':
  compose='https://x.com/intent/post?'+urlencode({'text':p['text']+('\n\n'+p['url'] if p['url'] else '')})
  cards+='<a class="button" target="_blank" rel="noopener noreferrer" href="'+html.escape(compose,quote=True)+'">Open X draft</a>'
 else:
  compose='https://www.reddit.com/r/SideProject/submit?'+urlencode({'type':'self','title':p['title'],'text':p['text']})
  cards+='<a class="button" target="_blank" rel="noopener noreferrer" href="'+html.escape(compose,quote=True)+'">Open Reddit draft</a>'
 if p['asset']:cards+='<a class="button secondary" href="'+p['asset']+'" download>Download attachment</a>'
 cards+='</article>'
page='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VisitorPing · Free launch</title><style>'+style+'</style><main><header><div class="brand">VisitorPing</div><span>$0 ad spend · X + Reddit</span></header><h1>Your free launch.<br><span class="green">Ready to review.</span></h1><p>Three X drafts and one Reddit introduction. Nothing published yet. Prepared for X @serhansarii and Reddit u/serhansari83. Authenticated publishing access is still needed. Draft buttons open on your device; check the signed-in account before submitting. Video attachments must be added in the platform composer.</p><p>The launch uses the existing homepage, so it does not depend on deploying the campaign landing page.</p><a class="button" href="visitorping-campaign.zip" download>Download launch package</a><section class="section"><h2>The demo</h2><video controls playsinline preload="metadata" poster="assets/video-poster.png"><source src="assets/visitorping-demo.mp4" type="video/mp4"></video><p class="muted">15-second explainer. Example data and illustrative notification.</p></section>'+cards+'<section class="section"><h2>Publishing approach</h2><p>Check account history and eligibility first. Lead with the X video and one eligible r/SideProject post. Review real responses before writing follow-ups; do not repeat the same pitch in unrelated threads.</p><p>r/SaaS is excluded because its rules prohibit AI-generated text. r/SideProject requests the Project name - Short description title format; account-specific eligibility still needs checking.</p><p>First target: five website owners who install tracking and experience their first visitor. This is a target, not a promise. Attribution from a post to activation is not yet verified.</p><p><a href="https://www.reddit.com/r/SideProject/about.json">SideProject submission guidance</a> · <a href="https://www.reddit.com/r/SaaS/about/rules.json">SaaS rules</a></p></section></main></html>'
(root/'index.html').write_text(page)
md='# Active free launch\n\nAd spend is $0. Paid plan is superseded. No paid tools or subscriptions are authorized by this plan.\n\n'
for p in posts:md+='## '+p['platform']+' / '+p['id']+'\n\n'+(p.get('title','')+'\n\n' if p.get('title') else '')+p['text']+'\n\n'+(p['url']+'\n\n' if p['platform']=='X' and p['url'] else '')
md+='## Pending\n\nHandles supplied: X @serhansarii and Reddit u/serhansari83. Public history could not be verified: Reddit returned HTTP 403; X exposed no posts in the unauthenticated browser. Authenticated publishing access and account-specific community eligibility remain unverified. No connected X/Reddit publishing tool exists in this session. No posts or DMs sent. No ongoing monitoring scheduled.\n'
Path('marketing/visitorping-launch/organic-launch.md').write_text(md)
with zipfile.ZipFile(root/'visitorping-campaign.zip','w',zipfile.ZIP_DEFLATED) as z:
 for name in ['index.html','campaign.json','assets/ad-notification.png','assets/ad-refreshing.png','assets/visitorping-demo.mp4','assets/video-poster.png']:z.write(root/name,name)
 z.write('marketing/visitorping-launch/organic-launch.md','organic-launch.md')
print('Free launch page, four drafts, $0 manifest and ZIP updated; X drafts fit standard post length.')
